alias: Controleer Lampen Zonder Stroom ook badkamer
description: ""
triggers:
  - minutes: /5
    trigger: time_pattern
actions:
  - variables:
      fs_lampen: |
        {{ states.light
           | selectattr('attributes.friendly_name', 'search', 'FS')
           | map(attribute='entity_id')
           | list }}
  - target:
      entity_id: input_text.lampen_zonder_stroom
    data:
      value: ""
    action: input_text.set_value
  - repeat:
      for_each: "{{ fs_lampen }}"
      sequence:
        - variables:
            lamp_entity: "{{ repeat.item }}"
            lamp_name: "{{ states[lamp_entity].attributes.friendly_name }}"
            huidige_helderheid: "{{ state_attr(lamp_entity, 'brightness') | int(0) }}"
            nieuwe_helderheid: |
              {% if huidige_helderheid == 255 %}
                254
              {% elif huidige_helderheid == 254 %}
                253
              {% else %}
                {{ huidige_helderheid + 1 if huidige_helderheid + 1 <= 254 else 254 }}
              {% endif %}
        - target:
            entity_id: "{{ lamp_entity }}"
          data:
            brightness: "{{ nieuwe_helderheid }}"
          action: light.turn_on
        - delay:
            seconds: 5
        - variables:
            aangepaste_helderheid: "{{ state_attr(lamp_entity, 'brightness') | int(0) }}"
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ aangepaste_helderheid != nieuwe_helderheid }}"
              sequence:
                - data:
                    message: >
                      Lamp zonder stroom: {{ lamp_name }} ({{ lamp_entity }}). 
                      Helderheidswijziging niet doorgevoerd.
                    title: Lamp zonder stroom gedetecteerd
                  action: persistent_notification.create
                - target:
                    entity_id: input_text.lampen_zonder_stroom
                  data:
                    value: >
                      {% set huidige_waarde =
                      states('input_text.lampen_zonder_stroom') %} {% if
                      huidige_waarde %}
                        {{ huidige_waarde }}, {{ lamp_entity }}
                      {% else %}
                        {{ lamp_entity }}
                      {% endif %}
                  action: input_text.set_value
        - target:
            entity_id: "{{ lamp_entity }}"
          data:
            brightness: "{{ huidige_helderheid }}"
          action: light.turn_on
        - delay:
            seconds: 1