alias: Check Lamps Without Power
description: ""
triggers:
  - minutes: /5
    trigger: time_pattern
actions:
  - variables:
      active_lamps: |
        {{ states.light
           | selectattr('attributes.friendly_name', 'defined')
           | map(attribute='entity_id')
           | list }}
  - target:
      entity_id: input_text.excluded_lamps
    data:
      value: ""
    action: input_text.set_value
  - repeat:
      for_each: "{{ active_lamps }}"
      sequence:
        - variables:
            lamp_entity: "{{ repeat.item }}"
            lamp_name: "{{ states[lamp_entity].attributes.friendly_name }}"
            current_brightness: "{{ state_attr(lamp_entity, 'brightness') | int(0) }}"
            new_brightness: |
              {% if current_brightness == 255 %}
                254
              {% elif current_brightness == 254 %}
                253
              {% else %}
                {{ current_brightness + 1 if current_brightness + 1 <= 254 else 254 }}
              {% endif %}
        - target:
            entity_id: "{{ lamp_entity }}"
          data:
            brightness: "{{ new_brightness }}"
          action: light.turn_on
        - delay:
            seconds: 5
        - variables:
            adjusted_brightness: "{{ state_attr(lamp_entity, 'brightness') | int(0) }}"
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ adjusted_brightness != new_brightness }}"
              sequence:
                - data:
                    message: >
                      Lamp without power: {{ lamp_name }} ({{ lamp_entity }}). 
                      Brightness adjustment failed.
                    title: Lamp without power detected
                  action: persistent_notification.create
                - target:
                    entity_id: input_text.excluded_lamps
                  data:
                    value: >
                      {% set current_value =
                      states('input_text.excluded_lamps') %} {% if
                      current_value %}
                        {{ current_value }}, {{ lamp_entity }}
                      {% else %}
                        {{ lamp_entity }}
                      {% endif %}
                  action: input_text.set_value
        - target:
            entity_id: "{{ lamp_entity }}"
          data:
            brightness: "{{ current_brightness }}"
          action: light.turn_on
        - delay:
            seconds: 1